# -*- coding: utf-8 -*-
"""2D Grid Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13HZCLAIwhNo9fiVaw3Om9N-DbKbT8-FE

# 2D Mapped Grid Generator — Finite Volume Method (FVM)

## Points Generator
"""

import numpy as np
from numpy import pi, sqrt
import matplotlib.pyplot as plt

# ---------------- Shape functions ----------------
def q9_shape_functions(xi, eta):
    # 1D quadratic Lagrange polynomials
    L1 = 0.5 * xi * (xi - 1.0)
    L2 = 1.0 - xi**2
    L3 = 0.5 * xi * (xi + 1.0)

    M1 = 0.5 * eta * (eta - 1.0)
    M2 = 1.0 - eta**2
    M3 = 0.5 * eta * (eta + 1.0)

    # Tensor-product shape functions (Q9)
    N = np.array([
        L1*M1,  # N1 (-1,-1)
        L3*M1,  # N2 ( 1,-1)
        L3*M3,  # N3 ( 1, 1)
        L1*M3,  # N4 (-1, 1)
        L2*M1,  # N5 ( 0,-1)
        L3*M2,  # N6 ( 1, 0)
        L2*M3,  # N7 ( 0, 1)
        L1*M2,  # N8 (-1, 0)
        L2*M2   # N9 ( 0, 0)
    ])
    return N

# --------------- Interpolation -------------------
def q9_interpolate_points(ctrl_pts, natural_coords):
    """
    Interpolate many physical coordinates (X,Y) using Q9 shape functions.

    Parameters
    ----------
    ctrl_pts : (9,2) array_like
        Control-point coordinates ordered as:
        [(-1,-1), ( 1,-1), ( 1, 1), (-1, 1),
         ( 0,-1), ( 1, 0), ( 0, 1), (-1, 0), ( 0, 0)]
    natural_coords : (m,2) array_like
        Each row is (xi, eta) in [-1,1]^2.

    Returns
    -------
    structural_coords : (m,2) ndarray
        Interpolated points.
    """
    ctrl_pts = np.asarray(ctrl_pts, dtype=float).reshape(9, 2)
    natural_coords = np.asarray(natural_coords, dtype=float).reshape(-1, 2)

    # Build matrix of shape functions for all query points
    Nmat = np.vstack([q9_shape_functions(xi, eta) for xi, eta in natural_coords])  # (m,9)

    # Interpolate all points at once
    structural_coords = Nmat @ ctrl_pts  # (m,2)
    return structural_coords

# -------- Discretization in natural coordinates --------
nHeight = 11
nWidth  = 11

h = np.linspace(-1, 1, nHeight)  # eta
w = np.linspace(-1, 1, nWidth)   # xi
H, W = np.meshgrid(h, w)          # default 'xy': W->xi, H->eta

# (xi, eta) rows
natural_coords = np.column_stack((W.ravel(), H.ravel()))

# -------- Control points (example) --------
ctrl = np.array([
    [-1.0, -1.0],    # N1  (-1,-1)
    [ 1.0, -1.0],    # N2  ( 1,-1)
    [ 1.0,  1.0],    # N3  ( 1, 1)
    [-1.0,  1.0],    # N4  (-1, 1)
    [ 0.0, -1.0],    # N5  ( 0,-1)
    [ 1.0,  0.0],    # N6  ( 1, 0)
    [ 0.0,  1.0],    # N7  ( 0, 1)
    [-1.0,  0.0],    # N8  (-1, 0)
    [ 0.0,  0.0]     # N9  ( 0, 0)
])

# -------- Coordinate transformation --------
structural_coords = q9_interpolate_points(ctrl, natural_coords)

# ---------------- Plot ----------------
plt.figure(figsize=(8, 6))
plt.scatter(structural_coords[:, 0], structural_coords[:, 1], s=20, marker='o')

for i, (x, y) in enumerate(structural_coords):
    plt.text(x + 1e-3, y + 1e-3, str(i), fontsize=7, color='red')

plt.title('Structural Grid Points')
plt.xlabel('Width (X)')
plt.ylabel('Height (Y)')
plt.grid(True)
plt.axis('equal')
plt.show()